---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: demo_PostProvision
    inherits: 
    description: 
  fields:
  - common_meth1:
      value: wait_for_ip
  - vmware_meth1:
      value: vmware_PostProvision
  - redhat_meth1:
      value: redhat_PostProvision
